name: test action-clippy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check clippy version
        run: cargo clippy --version

      - uses: ./
        with:
          working_directory: ./test
          level: warning
          reporter: github-check
          filter_mode: nofilter
