name: test action-clippy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check clippy version
        run: cargo clippy --version

      - uses: ./
        with:
          working_directory: ./test
          level: warning
          reporter: github-check
          filter_mode: nofilter
