name: test action-clippy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check clippy version
        run: cargo clippy --version

      - uses: ./
        with:
          working_directory: ./test
          level: warning
          reporter: github-check
          filter_mode: nofilter
